export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";

export const CREATE_STREAM = "CREATE_STREAM";
export const CREATE_STREAM_START = "CREATE_STREAM_START";
export const CREATE_STREAM_SUCCESS = "CREATE_STREAM_SUCCESS";
export const CREATE_STREAM_FAIL = "CREATE_STREAM_FAIL";

export const FETCH_STREAMS_START = "FETCH_STREAMS_START";
export const FETCH_STREAMS_SUCCESS = "FETCH_STREAMS_SUCCESS";
export const FETCH_STREAMS_FAIL = "FETCH_STREAMS_FAIL";

export const FETCH_STREAM_START = "FETCH_STREAM_START";
export const FETCH_STREAM_SUCCESS = "FETCH_STREAM_SUCCESS";
export const FETCH_STREAM_FAIL = "FETCH_STREAM_FAIL";

export const DELETE_STREAM_START = "DELETE_STREAM_START";
export const DELETE_STREAM_SUCCESS = "DELETE_STREAM_SUCCESS";
export const DELETE_STREAM_FAIL = "DELETE_STREAM_FAIL";

export const EDIT_STREAM_START = "EDIT_STREAM_START";
export const EDIT_STREAM_SUCCESS = "EDIT_STREAM_SUCCESS";
export const EDIT_STREAM_FAIL = "EDIT_STREAM_FAIL";
